### ISSUE TITLE
No streaming, just a blackscreen

### ISSUE THREAD

**Issue by hot22shot** [Nonary/Sunshine#87]
### Bug Symptoms

Hello,

I'm using vibeshine (version 1.9.2) as a replacement of Apollo.
Host is a headless mini PC without physical monitor but with a kvm over ip plugged on an hdmi port.
Vibeshine is configured to use a virtual display (per client) exclusive.

I had some issue with the pairing pc client, moonlight 6.1 on bazzite, like timeout, bad pin code. But I could make it pair with vibeshine.

After that any connexion to the host is a blackscreen. I tried to change some parameters wihtout any luck.

### Expected Behavior

A stream !

### Windows Version

25H2

### Logs (Optional but Recommended)

I see 2 errors : 
The first one about no audio due to no steam installation : not issue for me, I use vibeshine to manage the pc, not to play. And it doesn't see to be a blocking point according to the logs.
The second error is about sunshine display helper, I do not understand this one  but it seems to be the root cause of the blackscreen.

```
[2025-11-19 17:38:12.495]: Info: A mouse was not detected. Sunshine will enable Mouse Keys while streaming to force the mouse cursor to appear.
[2025-11-19 17:38:12.507]: Info: CLIENT CONNECTED
[2025-11-19 17:38:12.526]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=0 target=259) completed in 7 ms
[2025-11-19 17:38:12.527]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=1 target=259) completed in 1 ms
[2025-11-19 17:38:12.529]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=2 target=259) completed in 1 ms
[2025-11-19 17:38:12.531]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=3 target=259) completed in 1 ms
[2025-11-19 17:38:12.532]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=4 target=259) completed in 1 ms
[2025-11-19 17:38:12.534]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=5 target=259) completed in 1 ms
[2025-11-19 17:38:12.535]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=6 target=259) completed in 1 ms
[2025-11-19 17:38:12.537]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=7 target=259) completed in 1 ms
[2025-11-19 17:38:12.538]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=8 target=259) completed in 1 ms
[2025-11-19 17:38:12.540]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:56721] source=9 target=259) completed in 1 ms
[2025-11-19 17:38:12.540]: Info: WinApiLayer::getDisplayScale (display=\\.\DISPLAY4 width=3840 height=2160) completed in 0 ms
[2025-11-19 17:38:12.540]: Info: WinApiLayer::getHdrState (adapter=[0:56721] source=0 target=259) completed in 0 ms
[2025-11-19 17:38:12.545]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:33206] source=0 target=49) completed in 4 ms
[2025-11-19 17:38:12.547]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:33206] source=1 target=49) completed in 1 ms
[2025-11-19 17:38:12.549]: Info: WinApiLayer::getSupportedDisplayModes (adapter=[0:33206] source=2 target=49) completed in 1 ms
[2025-11-19 17:38:12.549]: Info: WinApiLayer::getDisplayScale (display=\\.\DISPLAY1 width=1920 height=1080) completed in 0 ms
[2025-11-19 17:38:12.549]: Info: WinApiLayer::getHdrState (adapter=[0:33206] source=0 target=49) completed in 0 ms
[2025-11-19 17:38:12.696]: Info: 
Device Description : Intel(R) Graphics
Device Vendor ID   : 0x00008086
Device Device ID   : 0x000046D4
Device Video Mem   : 128 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8076 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 1920x0
Virtual Desktop    : 5760x2160
[2025-11-19 17:38:12.697]: Info: Active GPU has HAGS disabled
[2025-11-19 17:38:12.697]: Info: Using realtime GPU priority
[2025-11-19 17:38:12.697]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 10
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.150391,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0 nits
Max Luminance      : 3805.55 nits
Max Full Luminance : 3805.55 nits
[2025-11-19 17:38:12.698]: Info: Desktop resolution [3840x2160]
[2025-11-19 17:38:12.698]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2025-11-19 17:38:12.698]: Info: Display refresh rate [59.94Hz]
[2025-11-19 17:38:12.698]: Info: Requested frame rate [60fps]
[2025-11-19 17:38:12.699]: Info: Creating encoder [hevc_qsv]
[2025-11-19 17:38:12.699]: Info: Adjusted capture rate to 59.94fps to better match display
[2025-11-19 17:38:12.699]: Info: Color coding: SDR (Rec. 601)
[2025-11-19 17:38:12.699]: Info: Color depth: 8-bit
[2025-11-19 17:38:12.699]: Info: Color range: MPEG
[2025-11-19 17:38:12.719]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2025-11-19 17:38:12.965]: Error: Couldn't get default audio endpoint [0x80070490]
[2025-11-19 17:38:13.056]: Info: Steam audio drivers not found. This is expected if you don't have Steam installed.
[2025-11-19 17:38:13.057]: Error: Couldn't get default audio endpoint [0x80070490]
[2025-11-19 17:38:13.057]: Warning: There will be no audio
[2025-11-19 17:38:13.057]: Error: Unable to initialize audio capture. The stream will not have audio.
[2025-11-19 17:38:13.076]: Info: Streaming bitrate is 118988000
[2025-11-19 17:38:13.225]: Info: Minimum FPS target set to ~10fps (100ms)
[2025-11-19 17:38:15.496]: Info: Update check trigger accepted (force=true)
[2025-11-19 17:38:15.497]: Info: Update check: querying GitHub releases from repo Nonary/vibeshine
[2025-11-19 17:38:15.884]: Info: Update check: latest stable tag=1.9.0
[2025-11-19 17:38:15.884]: Info: Update check (tag-based): up-to-date. installed=1.9.2, stable=1.9.0, prerelease=
[2025-11-19 17:38:18.016]: Error: Failed to retrieve user token while launching: C:\Program Files\Sunshine\tools\sunshine_display_helper.exe
[2025-11-19 17:38:18.017]: Error: Failed to start display helper: C:\Program Files\Sunshine\tools\sunshine_display_helper.exe
[2025-11-19 17:38:18.369]: Info: CLIENT DISCONNECTED
[2025-11-19 17:38:18.778]: Info: Session ended
[2025-11-19 17:38:21.132]: Info: Virtual display devices have been removed successfully.
[2025-11-19 17:38:21.136]: Error: Failed to retrieve user token while launching: C:\Program Files\Sunshine\tools\sunshine_display_helper.exe
[2025-11-19 17:38:21.136]: Error: Failed to start display helper: C:\Program Files\Sunshine\tools\sunshine_display_helper.exe
[2025-11-19 17:38:21.136]: Info: Display helper unavailable; cannot send revert.
```

### Screenshot (Optional)

```image

```

**Comment by hot22shot** [comment]
I tried to install Steam but without any luck, and I just tested with 1.9.0 : same error.

**Comment by Nonary** [comment]
I think its fixed in v1.9.3 now

**Comment by hot22shot** [comment]
Thanks for your fast answer, I tested this morning and I still have the issue.
Here's the exported logs : 
[vibeshine_logs-20251121-073628.zip](https://github.com/user-attachments/files/23669622/vibeshine_logs-20251121-073628.zip)

**Comment by hot22shot** [comment]
So I actually got it working by rebooting the host.

I'm also using the host through RDP and I wonder if it plays well with Sunshine.

**Comment by Nonary** [comment]
> I'm also using the host through RDP and I wonder if it plays well with Sunshine.

That is known to cause issues with Sunshine in general because it signs off the account

**Comment by hot22shot** [comment]
I noticed apollo has a different behavior when a rdp session is present, instead of a blackscreen the stream establishment fails but it works on the second time.

Do you think you could make it so that there is no need to reboot the server ?

**Comment by Nonary** [comment]
I am not sure why the black screens happens on your setup, you have a headless host that is reporting active monitors but the monitors themselves are just dead.

**Comment by Nonary** [comment]
Okay, I changed how the display API works in v1.10.3 and it should work now just keep in mind if you use extended (no primary) the login screen on windows will intentionally be blacked out until you click it. If using exclusive (default) or extended + primary it should show up with no issues.

**Comment by hot22shot** [comment]
Thank you ! I have downloaded the latest version 1.10.3, I'll make some tests and let you know.

**Comment by Nonary** [comment]
@hot22shot Did this issue resolve for you?

**Comment by hot22shot** [comment]
Yes and no : the issue was solved but I don't think it was from something you changed.

In the configuration of the kvm over ip I use (a pcie nanokvm from https://github.com/sipeed/NanoKVM) I just disconnected the hdmi signal from the webui so that the host has no screen at all.
I think it would be equivalent to turning off a physical monitor.

In retrospect I think the blackscreen I got was what you explained : 

> the login screen on windows will intentionally be blacked out until you click it

But what I don't understand is why I had this blackscreen in exclusive mode, as my nanokvm should have been detected as a physical monitor.

Anyway I have now a working setup, that's all I wanted, thanks !
